### ISSUE TITLE
Non-video crashing app

### ISSUE THREAD

**Issue by braderhart** [lbryio/lbry-fdroid#13]
### Steps to reproduce
1. Search for ed25519 on LBRY
2. Click on the first [video](https://odysee.com/ed255c9e-dd5c-4fbd-894b-37c9192f8ded:d)
3. The app crashes

### Expected behaviour
The app shouldn't crash

### Actual behaviour
The app crashes

## System Configuration
- Device: moto one action
- Android version: 11

**Comment by kekkyojin** [comment]
This is not specific to FDroid.

Crash report
-----------------

`2021-05-03 17:48:13.965 2189-2189/io.lbry.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.lbry.browser, PID: 2189
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List io.lbry.browser.model.Claim.getTags()' on a null object reference
        at io.lbry.browser.ui.findcontent.FileViewFragment.checkAndLoadComments(FileViewFragment.java:1707)
        at io.lbry.browser.ui.findcontent.FileViewFragment.checkParams(FileViewFragment.java:480)
        at io.lbry.browser.ui.findcontent.FileViewFragment.onResume(FileViewFragment.java:748)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
`
